# Generated by Django 4.2 on 2023-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_monster_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Small_Monster_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('image', models.CharField()),
            ],
        ),
    ]
